baseURL = "https://tehgm.net/"
languageCode = "en-gb"
title = "TehGM"
theme = "LoveIt-0.2.10"
images = [ "https://cdn.tehgm.net/global/img/tehgm_avatar.png" ]

[permalinks]
	blog = "/:sections/:slug"
	categories = "/blog/categories/:slug"
	tags = "/blog/tags/:slug"

[params]
	version = "0.2.X"
	dateFormat = "02.01.2006"
	defaultTheme = "dark"
	description = "ASP.NET Core programmer by profession. Gamer and developer of libraries and bots by hobby. This is my personal website - technology, personal thoughts, and more."

	[params.app]
		title = "TehGM"

	[params.header.title]
		name = "TehGM"
		typeit = true

	[params.footer]
		hugo = false

	[params.page]
		lightgallery = true

		[params.page.toc]
			auto = false

	[params.home.profile]
		enable = true
		social = true
		avatarURL = "https://cdn.tehgm.net/global/img/tehgm_avatar.png"
		title = "TehGM"
		subtitle = "ASP.NET Core programmer by profession; <br/> Gamer and developer of libraries and bots by hobby;"
	[params.home.posts]
		enable = false
	[params.social]
		GitHub = "TehGM"
		Twitter = "TehOriginalGM"
		Youtubecustom = "TehGM"
		Reddit = "TehGM"
		Stackoverflow = "TehGM"
		Patreon = "TehGMdev"
		Steam = "TehGM"
		Twitch = "TehGM"
		Email = "admin@tehgm.net"

	[params.seo]
		image = "https://cdn.tehgm.net/global/img/tehgm_avatar.png"
		thumbnail = "https://cdn.tehgm.net/global/img/tehgm_avatar.png"

[author]
	name = "TehGM"
	email = "admin@tehgm.net"
	link = "https://tehgm.net"


[menu]
	[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/blog/"
	title = "Blog"
	weight = 1