baseURL = "https://tehgm.net/"
languageCode = "en-gb"
title = "TehGM"
theme = "LoveIt-0.2.10"
enableRobotsTXT = true
enableEmoji = true

[permalinks]
	blog = "/:sections/:slug"
	categories = "/blog/categories/:slug"
	tags = "/blog/tags/:slug"

[params]
	version = "0.2.X"
	dateFormat = "02.01.2006"
	defaultTheme = "dark"
	description = "ASP.NET Core programmer by profession. Gamer and developer of libraries and bots by hobby. My personal website - technology, personal thoughts, and more."
	images = [ "/img/tehgm_avatar.png" ]

	[params.app]
		title = "TehGM"

	[params.header.title]
		name = "TehGM"
		typeit = true

	[params.footer]
		hugo = false

	[params.page]
		lightgallery = true

		[params.page.toc]
			auto = false

		[params.page.code]
			copy = true
			lineNumbersInTable = true

		[params.page.share]
			enable = true
			Twitter = true
			Facebook = true
			Whatsapp = true
			HackerNews = true
			Reddit = true
			Myspace = true
			Tumblr = true

		[params.page.library]
			[params.page.library.js]
				jQuery = "https://code.jquery.com/jquery-3.5.1.min.js"
				spoiler = "js/spoiler.js"

	[params.home.profile]
		enable = true
		social = true
		avatarURL = "/img/tehgm_avatar.png"
		title = "TehGM"
		subtitle = "ASP.NET Core programmer by profession; <br/> Gamer and developer of libraries and bots by hobby;"
	[params.home.posts]
		enable = false
	[params.social]
		GitHub = "TehGM"
		Twitter = "TehOriginalGM"
		Youtubecustom = "TehGM"
		Reddit = "TehGM"
		Stackoverflow = "4644581/tehgm?tab=profile"
		Patreon = "TehGMdev"
		Steam = "TehGM"
		Twitch = "TehGM"
		Email = "admin@tehgm.net"

	[params.seo]
		image = "/img/tehgm_avatar.png"
		thumbnailUrl = "/img/tehgm_avatar.png"

[author]
	name = "TehGM"
	email = "admin@tehgm.net"
	link = "https://tehgm.net"


[menu]
	[[menu.main]]
	identifier = "home"
	name = "Home"
	url = "/"
	title = "Home"
	weight = 1
	[[menu.main]]
	identifier = "blog"
	name = "Blog"
	url = "/blog/"
	title = "Blog"
	weight = 2
	[[menu.main]]
	identifier = "imo"
	name = "IMO"
	url = "/blog/imo/"
	title = "Blog: IMO"
	weight = 3

[markup]
	[markup.highlight]
		codeFences = true
		lineNos = true
		noClasses = false
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true

[sitemap]
	changefreq = "weekly"
	filename = "sitemap.xml"
	priority = 0.5